version: '3.7'

services:
  dashboard-soesport:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - node_mod

networks:
  node_mod:
    name: node_mod

volumes:
  node_modules:
